# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='lhs_samples',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tuning_session',
            field=models.CharField(choices=[('tuning_session', 'Tuning Session'), ('no_tuning_session', 'No Tuning'), ('randomly_generate', 'Randomly Generate'), ('lhs', 'Run LHS')], default='tuning_session', max_length=64, verbose_name='session type'),
        ),
    ]
