# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_add_workload_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hyper_parameters',
            field=models.TextField(default='{}'),
        ),
    ]
