# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_change_result_taskids_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiontime',
            name='function',
            field=models.CharField(max_length=64),
        ),
    ]
