# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-02 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_change_executiontime_function_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='pipeline_knobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pipeline_knobs', to='website.PipelineData'),
        ),
        migrations.AddField(
            model_name='result',
            name='pipeline_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pipeline_metrics', to='website.PipelineData'),
        ),
    ]
