# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_add_pipeline_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionknob',
            name='lowerbound',
            field=models.CharField(max_length=32, null=True, verbose_name='lowerbound'),
        ),
        migrations.AddField(
            model_name='sessionknob',
            name='upperbound',
            field=models.CharField(max_length=32, null=True, verbose_name='upperbound'),
        ),
    ]
