# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_knob_bound_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='status',
            field=models.IntegerField(choices=[(1, 'MODIFIED'), (2, 'PROCESSING'), (3, 'PROCESSED')], default=1),
        ),
    ]
