# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_make_workload_status_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdata',
            name='other',
            field=models.TextField(default='{}'),
        ),
    ]
