FROM ottertune-base

COPY ./server /app

WORKDIR /app/website

COPY ./docker/credentials.py ./website/settings
COPY ./docker/start.sh ./docker/start-test.sh ./docker/wait-for-it.sh ./

RUN /install.sh web \
    && chmod +x ./*.sh \
    && sed s/'@localhost'/'@rabbitmq'/g ./website/settings/common.py > tmp \
    && mv tmp ./website/settings/common.py

ENV DJANGO_SETTINGS_MODULE=website.settings
ENV C_FORCE_ROOT=true

ENTRYPOINT ["./start.sh"]

